title: <img src="./logo.svg" alt="LoAT">
email: florian.frohn@cs.rwth-aachen.de
description: >- # this means to ignore newlines until "baseurl:"
  We present a novel calculus that allows for combining loop acceleration and non-termination techniques for loops operating on integers in a modular way.
github_username:  ffrohn
theme: jekyll-theme-cayman
github:
  is_project_page: false
